#pragma once

#define GROWLAB_DEVICE_UID "esp32-growlab-dev"
#define GROWLAB_FIRMWARE_VERSION "0.1.0-step14"

#define GROWLAB_WIFI_SSID "CHANGE_ME"
#define GROWLAB_WIFI_PASSWORD "CHANGE_ME"

#define GROWLAB_MQTT_HOST "192.168.1.10"
#define GROWLAB_MQTT_PORT 1883
#define GROWLAB_MQTT_USERNAME "growlab"
#define GROWLAB_MQTT_PASSWORD "change-me"

#define GROWLAB_RELAY_PIN 26
#define GROWLAB_PUMP_PIN 27
#define GROWLAB_RELAY_ACTIVE_LEVEL HIGH
#define GROWLAB_PUMP_ACTIVE_LEVEL HIGH

#define GROWLAB_HEARTBEAT_INTERVAL_MS 30000UL
#define GROWLAB_TELEMETRY_INTERVAL_MS 15000UL
#define GROWLAB_WIFI_RETRY_INTERVAL_MS 10000UL
#define GROWLAB_MQTT_RETRY_INTERVAL_MS 5000UL
