<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../GrowLab.Application/GrowLab.Application.csproj" />
    <ProjectReference Include="../GrowLab.Domain/GrowLab.Domain.csproj" />
    <ProjectReference Include="../GrowLab.Infrastructure/GrowLab.Infrastructure.csproj" />
    <ProjectReference Include="../../../packages/contracts/GrowLab.Contracts/GrowLab.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
